### ISSUE TITLE
Submission to the Astro Theme Portal

### ISSUE THREAD

**Issue by sarah11918** [diego-alfadev/alfadev-astro-starter#1]
Hi @diego-alfadev !

Your theme looks great, but I just wanted to let you know why your submission was denied. We need you to remove the Astro logo from your images and theme. We suggest coming up with your own logo for your own brand recognition! (This is also the old Astro logo and we are asking everyone to remove it from all sites and publications.)

Once you remove the logo and create new screenshots for your theme, please do upload it again to the theme portal and I will be happy to approve it! 🚀

**Comment by diego-alfadev** [comment]
Hello @sarah11918 , i've made the required changes, hope that it's okay now.
Ive also published the changes to https://astro-starter.alfadev.io/

Commits:
- 354683460d5dcbb287a3cf7ae8eba8b50d5bcf63
- 68a0ef0a8c7a692c3074393e6152347048fe898f
- b178a8718e3df7787120b91c5f51529688f6a4d1
- ed052e2e2b57690889edb20e53d02faccce123ff

Such a pleasure to me to be a small part of the Astro ecosystem, i love your sollution and i'll be looking forward for Astro to become the most popular javascript web framework for static pages, the developer experience deserves that!

Let me know if theres anything more i should do.

Best regards, Diego
